version: "3.6"

services:
 db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
    - ./.env.db
 web:
    build:
     context: .
     dockerfile: Dockerfile
    command: gunicorn PyEditorial.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/code
      - static:/code/static
      - media:/code/media
    ports:
      - "8000:8000"
    depends_on:
      - db   
 nginx:
    build: ./nginx
    volumes:
      - ./:/code
      - static:/code/static
      - media:/code/media
    ports:
      - "3000:80"
    depends_on:
    - web

volumes:
  postgres_data:
  static:
  media:
